#!/usr/bin/python
import os,sys,re
f=os.popen("netstat -nlt4","r")
if len(sys.argv)>1:
	start=int(sys.argv[1])
else:
	start=5900
s=set()
for line in f:
    if not line.startswith("tcp"):
        continue
    m=re.search(":(\\d+)\\b",line)
    if m:
        s.add(int(m.group(1)))
i=start
while i in s:
    i += 1
print i

        

